#!/bin/sh
ubuntu@ec2-3-16-30-166.us-east-2.compute.amazonaws.com <<EOF
    cd ~/node-app
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v14.15.4
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
